#!/usr/bin/env bash
# Bootstrap dotfiles configuration.

set -e

# install brew
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# install go (for mage) 
# brew install go

# install mage (https://github.com/magefile/mage)
# TODO: why need to do this. why not just go get .. (ask on slack)
# TODO: need to setup gopath 1st?
# git clone https://github.com/magefile/mage
# cd mage
# go run bootstrap.go
 
CONFIG=".install.conf.yaml"
DOTBOT_DIR="vendor/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
