" not utilising the power of it but I think it can be great
set relativenumber

" allows me to yank text to system clipboard
set clipboard=unnamed

syntax on

" vim-plug plugin manager
call plug#begin()
Plug 'tpope/vim-sensible'

call plug#end()

