" make navigation easier
set relativenumber
set number

" allows me to yank text to system clipboard
set clipboard=unnamed

" finally have a nice looking editor :D
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

" syntax highlighting
syntax on

" set terminal title
set title

" indentation
set smartindent

" plugins to use
call plug#begin()

" sensible defaults
Plug 'tpope/vim-sensible'

" go autocomplete
Plug 'fatih/vim-go'

" colour goodness
Plug 'morhetz/gruvbox'

" a nice looking status bar on the bottom
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" testing it out
Plug 'easymotion/vim-easymotion'

" Plug 'Shougo/deoplete.nvim' TODO:  need to get python 3 working

call plug#end()

" activate the colour scheme
colorscheme gruvbox
" set night mode
set background=dark 

