# source prezto
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/init.zsh"
fi

# vi movement in iTerm
set -o vi

# source everything
source ~/.dotfiles/zsh/zpaths
source ~/.dotfiles/zsh/zcd
source ~/.dotfiles/vim/zvim
source ~/.dotfiles/zsh/zfunctions
source ~/.dotfiles/zsh/zdev
source ~/.dotfiles/git/zgit
source ~/.dotfiles/zsh/zenv
source ~/.dotfiles/zsh/zalias
source ~/.dotfiles/zsh/zapp
source ~/.dotfiles/zsh/zscripts

# 'thefuck' command correction 
eval "$(thefuck --alias)"

# autojump > cd
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# zplug package manager
# todo: make it so I don't need to rely on specific ver number
source /usr/local/Cellar/zplug/2.3.2/init.zsh

# better than l file and dir listings with good info
zplug "supercrabtree/k"
zplug "Tarrasch/zsh-bd"

# source all zplug plugins and add commands to $PATH
zplug load


