# source prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# source aliases 
source ~/.dotfiles/zsh/zpaths
source ~/.dotfiles/zsh/zalias
source ~/.dotfiles/vim/zvim
source ~/.dotfiles/zsh/zfunctions
source ~/.dotfiles/zsh/zdev

# add bin to my path
export PATH=$PATH:~/.dotfiles/bin

# 'thefuck' command correction 
eval "$(thefuck --alias)"

export NODE_PATH='/usr/local/lib/node_modules'
export ZPLUG_HOME=/usr/local/opt/zplug 
source $ZPLUG_HOME/init.zsh





