# source prezto
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/zsh/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.dotfiles/zsh/init.zsh"
fi

export PATH=$(brew --prefix ruby)/bin:$PATH

# add bin to my path
export PATH=$PATH:~/.dotfiles/bin

# set up go path
export GOPATH=/Users/nikivi/go/
export PATH=$PATH:$GOPATH/bin:$GOPATH/bin

# vi movement in iTerm
set -o vi

# source aliases
source ~/.dotfiles/zsh/zpaths
source ~/.dotfiles/vim/zvim
source ~/.dotfiles/zsh/zfunctions
source ~/.dotfiles/zsh/zdev
source ~/.dotfiles/git/zgit
source ~/.dotfiles/zsh/zenv
source ~/.dotfiles/zsh/zalias

# 'thefuck' command correction 
eval "$(thefuck --alias)"


# autojump > cd
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# zplug package manager
source /usr/local/Cellar/zplug/2.1.0/init.zsh

# better than l file and dir listings with good info
zplug "supercrabtree/k"
zplug "Tarrasch/zsh-bd"

# source all zplug plugins and add commands to $PATH
zplug load

